name: Build & Test Ant-Attack

on:
  push:
    branches: [ main ]  # triggers every time we push to main

jobs:
  test-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Test if website builds
        run: |
          echo "Testing website..."
          ls -l  # just checks files exist 

  build-job:
    runs-on: ubuntu-latest
    needs: test-job  # build only runs if test-job succeeds
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build Docker image
        run: |
          docker build -t my-website .
