name: Build & Test Ant-Attack

on:
  push:
    branches: [ main ]  # triggers every time we push to main

jobs:
  test-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y python3 curl tidy

      - name: Validate HTML
        run: |
          echo "Validating HTML..."
          tidy -qe index.html

      - name: Run server test
        run: |
          echo "Starting test server..."
          python3 -m http.server 8080 &
          sleep 3
          curl -I http://localhost:8080


  build-job:
    runs-on: ubuntu-latest
    needs: test-job  # build only runs if test-job succeeds
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build Docker image
        run: |
          docker build -t my-website .
